dataset:
  Name: "STRSTAUG"
  data_root: "./../../data/STRSTAUG"
  base_size: 256
  crop_size: 256
  data_aug: true
  suffix: "png"
  num_workers: 8
  train_batch: 32
  test_batch: 32
  train_dir: "trainval"
  test_dir: "test"