net:
  net_name: "ABCNet"
  type: "EncoderDecoder"
  pretrained : "None"
  backbone: "None"
  decode_head: 
    type: "ABCNet"
    in_ch: 3
    out_ch: 1
    dim: 64
    ori_h: 256
    deep_supervison: true
  loss: 
    type: "SoftIouLoss"