optimizer:
  type: "SGD"
  setting:
    lr : 0.01
    weight_decay: 0.0005


lr_config:
  policy: "PolyLR"
  warmup: "linear"
  power: 0.9
  min_lr: 1e-4
  warmup_epochs: 5




runner:
  type: "EpochBasedRunner"
  max_epochs: 500


checkpoint_config:
  by_epoch: false
  interval: 1


evaluation:
  epochval: 1
  metric: "mIoU"
  pre_eval: true
  